### ISSUE TITLE
Cannot build when TMPDIR is mounted as noexec

### ISSUE THREAD

**Issue by cielavenir** [pycompression/python-isal#101]
We are copying isal source to TMPDIR and running autogen.sh inside TMPDIR, but if TMPDIR is mounted as noexec, autogen.sh will raise Error 13 Permission Denied. (In the specific environment) as a workaround we needed to `sudo mount -o remount,exec /tmp /tmp`.

If possible please fix setup.py to avoid this problem.

**Comment by rhpvorderman** [comment]
That would complicate things, as the prefix for the included ISA-L source needs to be build somewhere. Using the temporary directory is the best option. The temporary directory is obtained with python's tempfile module. So you can also run `TMPDIR=/path/to/somewhere pip install isal` to use another path.

Also wheels are provided for most platforms and python versions, so a build of ISA-L should not be triggered. Which platform are you building on? Did you upgrade to the latest version of pip?

**Comment by cielavenir** [comment]
ok, building in another directory worked (sorry my machine has /tmp exec and a colleague of mine has /tmp noexec so I needed to test using yet another directory than /tmp).

- For a reason I have to use Python2, so I need to strip type annotations. Of course I know it is not something to be merged, but that also means wheels are not expected.
- We use build orchestration system, so passing TMPDIR is a little difficult.

It could also be possible to fallback to Makefile.unx only when permission denied happens.

**Comment by cielavenir** [comment]
well, I just thought TMPDIR issue is out of the scope to backporting to Python2, so I felt like there could still be some people having the same issue.

meanwhile it is also true that I can keep my autogenless setup.py for my Py2 fork.

maybe please close this. sorry for confusion.

**Comment by rhpvorderman** [comment]
> For a reason I have to use Python2, so I need to strip type annotations. Of course I know it is not something to be merged, but that also means wheels are not expected.

When I started this project (september 2020) Python2 was officially not supported anymore for 9 months already. Type annotations are also not supported for python 3.4 and lower. This projects supports 3.6 and higher, partly because these are still supported, but also because it makes my life easier. (F-strings hurray!) Therefore I won't be supporting python 2.

I am not going to have python2 packages under the `isal` repository for the aforementioned reason. But since you already have a py2 fork, maybe you could create your own `isal-py2` package on PyPI and push wheels there? Using cibuildwheel that should be quite doable. Please have a rigorous reading trough setup.py and

- add python2 dependencies in setup_requires
- **Change the contact email to yours**. I don't want any python2 support requests ;-)
- Change the description to clarify that this is a fork that tracks the `isal` package.

Also the README will need some modificiation where all the references in the shield images should point specifically to python-isal-py2 and not this repository. 

Anyway. Quite some work to maintain the port and build a wheel. But maybe less intensive than hacking all the individual machines to make it install?

**Comment by cielavenir** [comment]
thank you for comment, fixed author field https://github.com/cielavenir/python-isal-py2/commit/f945d57e5896546e93da6fceb962df931792be20

**Comment by cielavenir** [comment]
closing
