### ISSUE TITLE
Building wheels for isal error

### ISSUE THREAD

**Issue by tistelac** [pycompression/python-isal#114]
('python=3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.21.0'

Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, 2712 Mhz, 4 Core(s), 8 Logical Processor(s)

  ## Traceback
Building wheels for collected packages: isal
  Building wheel for isal (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for isal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      cythoning src/isal/isal_zlib.pyx to src/isal\isal_zlib.c
      cythoning src/isal/igzip_lib.pyx to src/isal\igzip_lib.c
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for isal
Failed to build isal
ERROR: Could not build wheels for isal, which is required to install pyproject.toml-based projects

**Comment by rhpvorderman** [comment]
python-isal provides wheels for:

- Windows x86_64
- Linux x86_64
- MacOS x86_64
- Linux ARMv64

These are incidentally also the platforms that are supported by [ISA-L](https://github.com/intel/isa-l). 
If your machine is not supported (A Mac OS ARM laptop for instance). Then it cannot build.

Which package were you trying to install? I will put more information on the README, so that package maintainers know how to include python-isal as a dependency.

**Comment by rhpvorderman** [comment]
Okay, the extra information has been added. 
This is a problem in the `setup.py` or `setup.cfg` of whatever project you were trying to install? Can you please provide the name of this package? That way, I can rectify it with a pull request.

**Comment by tistelac** [comment]
_64 was the issue. With python 64 bit version I do not have this problem. Thanks!

**Comment by rhpvorderman** [comment]
Thanks for reporting back. Sorry I didn't spot the 32-bit. I did not expect that in 2022 :-) .
