### ISSUE TITLE
Python 3.11 wheels

### ISSUE THREAD

**Issue by zariiii9003** [pycompression/python-isal#127]
Could you upload 3.11 compatible wheels to PyPI?

**Comment by rhpvorderman** [comment]
I need to make sure python 3.11 can be tested first. But I see that this is possible with github actions. It will take me some time to make this in order and afterwards I can release the wheels. 

Have you tried compiling yourself in case you need it sooner?

**Comment by zariiii9003** [comment]
For me it is just a dependency of a dependency. Building while installing via pip fails on Windows. It is not urgent though.

**Comment by rhpvorderman** [comment]
Interesting. Which dependency if I may ask? If it is cutadapt -> xopen you can simply install using `pip install --no-deps xopen` and then install `pip install cutadapt`. the `isal` package in programs that I know of is usually optional.

Compiling on windows is a huge pain in the bottom area. I spent so much time getting that to work so I could build the wheels. I do not recommend that route. I am so happy that I figured it out so it is all nice and automated when I build the wheels and I never have to do it manually ever again.

The Python 11 tests pass. Since ABI compatibility is promised, these wheels should work with the production release of Python 3.11. I will start releasing a new version. I will report back on this issue when it is done.

**Comment by zariiii9003** [comment]
It's this package: https://github.com/danielhrisca/asammdf/blob/af0d4a6dacf04142fd3c4ddc6247f5bd71017224/requirements.txt#L8

Thank you for the update 👍

**Comment by danielhrisca** [comment]
> It's this package: https://github.com/danielhrisca/asammdf/blob/af0d4a6dacf04142fd3c4ddc6247f5bd71017224/requirements.txt#L8
> 
> Thank you for the update 👍

do you see any speed improvement with python 3.11 ?

**Comment by zariiii9003** [comment]
> do you see any speed improvement with python 3.11 ?

I don't know. I'm just trying to merge the mf4 PR into python-can 😄

**Comment by zariiii9003** [comment]
I'll close this as the wheel is available on PyPI now, thank you!

**Comment by rhpvorderman** [comment]
> do you see any speed improvement with python 3.11 ?

@danielhrisca for python-isal there should not be much speed improvement, as it is mostly a C-extension. Having said that the gzip.py GzipReader implementation has some overhead were quite some python methods are called. Python-isal uses a diffferent architecture than CPython's gzip implementation here though, so the overhead is already minimalized. This is currently being backported to CPython itself in a PR that should land in 3.12.

**Comment by danielhrisca** [comment]
Cool, I saw that there are speed improvements in cpython 3.11 but like you said mostly for pure python
