### ISSUE TITLE
isal installation fails in virtual env based on win32 cpython 3.8.10

### ISSUE THREAD

**Issue by msitkowski** [pycompression/python-isal#144]
Hi,
I have virtual env based on win32 cpython 3.8.10 and I cannot install isal package. Output log from `pip install isal` command looks like this:
![win32_cpython38_install_isal_fail_cmd](https://user-images.githubusercontent.com/6904499/229466072-57a78c0e-627e-4297-9ed8-f57f91903f08.png)

**Comment by rhpvorderman** [comment]
ISA-L is a 64-bit library and therefore won't install on 32-bit systems. 

Please use the 64-bit installation of python on windows. I did a check on the latest release (https://www.python.org/downloads/release/python-3112/) and it recommends the 64-bit installation.

For windows 64-bit wheels are provided, so it should be installed right away rather than trying to compile the package (which is what happens on your 32-bit installation now).

**Comment by msitkowski** [comment]
Ok, thanks for explanation.
