### ISSUE TITLE
Some questions about Arm64 and isa-l_crypto

### ISSUE THREAD

**Issue by yuhaoth** [pycompression/python-isal#24]
* Do you plan add isa-l_crypto binding ? It is crypto algorithm of isa-l . 
   ISA-L_crypto includes multi-buffer optimization for crypto algorithm and some special hash algorithm.

* Do you plan test this project on Arm64 platform ? 
  ISA-L for Arm64 has been done now.  I just want to know if you plan to test it on Arm64 .
  Travis CI can support Arm64 platform.  You can check isa-l/.travis.yml to know how to add Arm64 support

**Comment by rhpvorderman** [comment]
Hi @yuhaoth,

Thanks for taking an interest in this project. I am currently working as a bionformatician in the Leiden University Medical Center. In bioinformatics we use a lot of formats that depend on zlib-compatible compression in order to keep the large amounts of data manageable. That is why I have taken an interest in ISA-L, because of its very fast compression/decompression of zlib compatible formats.  So to answer your questions:

*  No. Crypto algorithms are not used extensively in bioinformatics. ISA-L_crypto is a different library as well. So I won't be the person who creates python-isal-crypto.
* I suppose adding a test could not hurt. This project uses Github actions for its CI. A quick lookup shows that they do not support ARM64 yet. Travis CI is essentially a paid service with a limited amount of time allotted to free users. It is also very very slow to run the tests on a free account. If ARM64 needs to be supported it would be best supported with a self-hosted github runner. But at our institute there are no ARM64 machines, so it is not a commitment I can make. If you are willing to put the time in to support ARM64 on this project I can grant you the access you need to make it work.

**Comment by yuhaoth** [comment]
Thanks @rhpvorderman . 

Travis CI is my nightmare also. I am working on ISA-L for Arm64 now. I just want to now if you will do those two thing.

**Comment by rhpvorderman** [comment]
Oh I forgot something. If you are interested in speeding up hashing it might be interesting to checkout [XXHash](https://github.com/Cyan4973/xxHash). It is **not** cryptographically secure, however it **is very good at providing a checksum for a file at very high speeds**. So if file integrity is your concern, xxhash is the way to go. Cryptographic security is not needed for file integrity. XXhash has bindings for python already.
